### ISSUE TITLE
Broken on Puppet 6 - cannot load f5 device - wrong number of arguments to Puppet::Util::Autoload#load (1, expects 2)

### ISSUE THREAD

**Issue by jessereynolds** [f5devcentral/f5-puppet#52]
In Puppet 5 and previous the second paramater to Puppet::Util::Autoload#load (env) is optional and set to nil by default. In Puppet 6 it is a required parameter, which Puppet::Util::NetworkDevice::F5::Device#initialize is not supplying.

```
Error: Can't load f5 for foo.example: wrong number of arguments (given 1, expected 2)
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/lib/puppet/util/autoload.rb:200:in `load'
/Users/jesse/.puppetlabs/etc/code/modules/f5/lib/puppet/util/network_device/f5/device.rb:15:in `initialize'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/lib/puppet/util/network_device.rb:8:in `new'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/lib/puppet/util/network_device.rb:8:in `init'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/lib/puppet/application/device.rb:259:in `block (2 levels) in main'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/lib/puppet/application/device.rb:245:in `each'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/lib/puppet/application/device.rb:245:in `collect'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/lib/puppet/application/device.rb:245:in `block in main'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/lib/puppet/context.rb:65:in `override'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/lib/puppet.rb:252:in `override'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/lib/puppet/application/device.rb:230:in `main'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/lib/puppet/application.rb:390:in `run_command'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/lib/puppet/application.rb:382:in `block in run'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/lib/puppet/util.rb:667:in `exit_on_fail'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/lib/puppet/application.rb:382:in `run'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/lib/puppet/util/command_line.rb:136:in `run'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/lib/puppet/util/command_line.rb:73:in `execute'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-6.0.2-universal-darwin/bin/puppet:5:in `<top (required)>'
/Users/jesse/.rbenv/versions/2.5.1/bin/puppet:23:in `load'
/Users/jesse/.rbenv/versions/2.5.1/bin/puppet:23:in `<main>'
```

**Comment by tkishel** [comment]
PRs 31 and 45 restore functionality for Puppet 6.
